name: CI-CD Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

     - name: Build
      run: mvn clean package -DskipTests
      shell: bash

    - name: Copy JAR
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.user }}
        key: ${{ inputs.key }}
        source: "target/*.jar"
        target: "/home/${{ inputs.user }}/app"
        strip_components: 1

    - name: Restart App
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.user }}
        key: ${{ inputs.key }}
        script: |
          fuser -k 8080/tcp || true
          nohup java -jar /home/${{ inputs.user }}/app/*.jar > app.log 2>&1 &


          
        
